DELETE FROM categories
WHERE slug IN (
    'minecraft-plugins',
    'minecraft-server-setups',
    'minecraft-builds',
    'minecraft-configs',
    'minecraft-graphics',
    'minecraft-textures',
    'minecraft-models',
    'minecraft-server-jars',
    'minecraft-skripts',
    'minecraft-other',
    'roblox',
    'roblox-game-setups',
    'roblox-maps',
    'roblox-scripts',
    'roblox-vehicles',
    'roblox-weapons',
    'roblox-models',
    'roblox-clothing',
    'roblox-graphics-ui',
    'roblox-animations-vfx',
    'roblox-audio',
    'hytale',
    'hytale-plugins',
    'hytale-data-assets',
    'hytale-server-setups',
    'hytale-builds',
    'hytale-graphics',
    'hytale-models',
    'hytale-other',
    'websites',
    'websites-standalone',
    'websites-tebex',
    'websites-pterodactyl',
    'websites-namelessmc',
    'websites-xenforo',
    'websites-invision-community',
    'websites-whmcs',
    'websites-paymenter',
    'websites-calagopus',
    'discord-bots',
    'discord-graphics',
    'discord-other'
);

DELETE FROM categories
WHERE slug IN (
    'minecraft',
    'roblox',
    'hytale',
    'websites',
    'discord'
);
